services:
  message_service:
    build: ./message-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./message-service/:/app/
    ports:
      - 8003:8000
    environment:
      - DATABASE_URI=${DATABASE_URL}
      # - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - movie_service
      - message_service

# volumes:
#   # postgres_data_movie:
#   postgres_data_message: