services:
  message_service:
    build: ./message-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./message-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=${DATABASE_URL}
      # - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
    depends_on:
      - message_db

  message_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_message:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=message_db_username
      - POSTGRES_PASSWORD=message_db_password
      - POSTGRES_DB=message_db_dev

  nginx:
    image: nginx:latest
    ports:
      - "8082:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - movie_service
      - message_service

volumes:
  # postgres_data_movie:
  postgres_data_message: